"""End-to-end tests for the two seams that touch a real OrcaSlicer build.

Everything here was previously untested -- test_wave_core.py covers the pure
geometry, but nothing drove `WaveOverhangsSlicing.execute(ctx)`. That gap is
why the plugin shipped as a silent no-op.

The object under test is a synthetic flat overhang: a 10x10 mm column that
steps out to 30x10 mm at z = 1.2, giving 20 x 10 mm of unsupported area.
"""
import importlib.util
import json
import os
import sys
from pathlib import Path

import pytest
from shapely.geometry import box

sys.path.insert(0, str(Path(__file__).parent))
# src/ too: the plugin does `import wave_core` there, and build.py inlines it.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
import fake_orca  # noqa: E402

# Point WAVE_PLUGIN_PATH at the built single-file plugin to run this same
# suite against the artifact users actually install (build.py inlines
# wave_core, so the built file must behave identically).
SRC = Path(os.environ.get(
    "WAVE_PLUGIN_PATH",
    Path(__file__).resolve().parents[1] / "src" / "wave_overhangs_orca.py"))
LAYER_H = 0.2
STEP_Z = 1.2  # first overhanging layer


def build_layers():
    layers = []
    z = LAYER_H
    while z < 2.0 + 1e-9:
        poly = box(0, 0, 10, 10) if z < STEP_Z - 1e-9 else box(0, 0, 30, 10)
        layers.append(fake_orca.Layer(round(z, 3), [poly]))
        z = round(z + LAYER_H, 3)
    return layers


@pytest.fixture
def plugin(tmp_path, monkeypatch):
    """Import the plugin source against the fake orca module, per test."""
    orca = fake_orca.install()
    sys.modules.pop("wave_overhangs_orca", None)
    spec = importlib.util.spec_from_file_location("wave_overhangs_orca", SRC)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["wave_overhangs_orca"] = mod
    spec.loader.exec_module(mod)
    # keep the plugin's diagnostics out of the source tree
    log = tmp_path / "wave.jsonl"
    monkeypatch.setattr(mod, "_write_log",
                        lambda e: log.open("a").write(json.dumps(e, default=str) + "\n"))
    mod._log_path = log
    mod._orca = orca
    mod._PLAN.clear()
    mod._CALIB = None
    return mod


def gcode_for(layers):
    """A minimal but realistic Orca export: layer markers + one outline each."""
    out = ["; generated by fake Orca\n", "M83\n", ";HEIGHT:0.2\n"]
    for layer in layers:
        minx, miny, maxx, maxy = layer.polygon_mm().bounds
        out.append(f";LAYER_CHANGE\n;Z:{layer.slice_z}\n")
        out.append(f"G1 Z{layer.slice_z} F600\n")
        out.append(";TYPE:Outer wall\n")
        out.append(f"G1 X{minx:.3f} Y{miny:.3f} E0.1\n")
        out.append(f"G1 X{maxx:.3f} Y{miny:.3f} E0.5\n")
        out.append(f"G1 X{maxx:.3f} Y{maxy:.3f} E0.5\n")
        out.append(f"G1 X{minx:.3f} Y{maxy:.3f} E0.5\n")
    out.append("; EXECUTABLE_BLOCK_END\n")
    return "".join(out)


def run_slice(plugin, layers, config=None, wired=True):
    """Drive posSlice. `wired` = is the capability also a post-processing plugin."""
    cap = plugin.WaveOverhangsSlicing()
    if config:
        cap._config = json.dumps(config)
    po = fake_orca.FakePrintObject(layers)
    ctx = fake_orca.Ctx(
        fake_orca.Step.posSlice, obj=po,
        config={"post_process_plugin": ["Wave Overhangs"] if wired else []})
    return cap, cap.execute(ctx)


# --------------------------------------------------------------------------
# Seam 1: posSlice -- plan the waves and carve the overhang out of the slices
# --------------------------------------------------------------------------

def test_posslice_plans_waves_for_a_flat_overhang(plugin):
    layers = build_layers()
    _, res = run_slice(plugin, layers)
    assert res.status is fake_orca.PluginResult.Success, res.message
    assert plugin._PLAN, "no wave plan was stashed for an obvious flat overhang"
    assert any(z >= STEP_Z - 1e-9 for z in plugin._PLAN), \
        f"waves planned at the wrong heights: {sorted(plugin._PLAN)}"


def test_posslice_carves_the_overhang_out_of_the_slices(plugin):
    """The carve must actually reach the host. It used to raise and get eaten."""
    layers = build_layers()
    before = [layer.polygon_mm().area for layer in layers]
    _, res = run_slice(plugin, layers)
    after = [layer.polygon_mm().area for layer in layers]

    assert "carved" in res.message
    carved = int(res.message.split("carved")[0].split(",")[-1].strip())
    assert carved > 0, f"nothing was carved: {res.message}"
    assert any(a < b - 1e-6 for a, b in zip(after, before)), \
        "carve reported success but no layer footprint actually shrank"
    assert any(layer.make_slices_calls for layer in layers)


def test_carve_can_be_turned_off(plugin):
    layers = build_layers()
    before = [layer.polygon_mm().area for layer in layers]
    _, res = run_slice(plugin, layers, {"carve_overhang": False})
    after = [layer.polygon_mm().area for layer in layers]
    assert after == before
    assert plugin._PLAN, "planning should still happen with carving off"


def test_a_bare_expolygon_is_rejected_by_the_binding():
    """Pin the fake to the real binding's contract (this is what bit us)."""
    coll = fake_orca.SurfaceCollection()
    e = fake_orca.ExPolygon([[0, 0], [10, 0], [10, 10]])
    with pytest.raises(TypeError):
        coll.set(e, fake_orca.SurfaceType.stInternal)
    coll.set([e], fake_orca.SurfaceType.stInternal)
    assert len(coll.surfaces) == 1


# --------------------------------------------------------------------------
# Seam 2: psGCodePostProcess -- splice the wave moves into the export
# --------------------------------------------------------------------------

def test_gcode_seam_splices_the_planned_waves(plugin, tmp_path):
    layers = build_layers()
    cap, _ = run_slice(plugin, layers)
    planned = len(plugin._PLAN)
    assert planned

    path = tmp_path / "out.gcode"
    path.write_text(gcode_for(layers), encoding="utf-8")
    before = path.read_text(encoding="utf-8")

    ctx = fake_orca.Ctx(fake_orca.Step.psGCodePostProcess, gcode_path=str(path))
    res = cap.execute(ctx)

    assert res.status is fake_orca.PluginResult.Success, res.message
    assert "spliced" in res.message, res.message
    n = int(res.message.split("spliced")[1].split("layer")[0].strip())
    assert n > 0, f"the export seam ran but spliced nothing: {res.message}"
    after = path.read_text(encoding="utf-8")
    assert after != before, "G-code file was not modified"
    assert len(after) > len(before)


def test_gcode_seam_is_a_noop_without_a_plan(plugin, tmp_path):
    cap = plugin.WaveOverhangsSlicing()
    path = tmp_path / "out.gcode"
    path.write_text(gcode_for(build_layers()), encoding="utf-8")
    before = path.read_text(encoding="utf-8")
    ctx = fake_orca.Ctx(fake_orca.Step.psGCodePostProcess, gcode_path=str(path))
    res = cap.execute(ctx)
    assert res.status is fake_orca.PluginResult.Success
    assert path.read_text(encoding="utf-8") == before


def test_unrelated_steps_are_ignored(plugin):
    cap = plugin.WaveOverhangsSlicing()
    for step in (fake_orca.Step.posPerimeters, fake_orca.Step.posInfill,
                 fake_orca.Step.psSkirtBrim):
        res = cap.execute(fake_orca.Ctx(step, obj=fake_orca.FakePrintObject([])))
        assert res.status is fake_orca.PluginResult.Success
        assert not plugin._PLAN


# --------------------------------------------------------------------------
# The whole point: planning without splicing must never leave a hole
# --------------------------------------------------------------------------

def test_carving_without_a_gcode_seam_does_not_delete_the_overhang(plugin):
    """If the export seam will not run, carving would print a hole.

    A user who selects the capability only under `Slicing Pipeline Plugin`
    (and not as a post-processing plugin) gets posSlice but never
    psGCodePostProcess. Carving there removes the overhang from the slices
    and nothing ever puts it back.
    """
    layers = build_layers()
    before = [layer.polygon_mm().area for layer in layers]
    _, res = run_slice(plugin, layers, wired=False)
    after = [layer.polygon_mm().area for layer in layers]
    assert after == before, (
        "the overhang was carved out of the slices even though the G-code "
        "seam is not wired up -- that prints a hole")
    assert "Post-processing plugin" in res.message, (
        "the user was given no hint that the plugin is half-connected: "
        + res.message)


def test_reslicing_drops_the_stale_plan(plugin):
    """Re-slicing must not splice the previous slice's waves.

    posSlice fires per object with no "new run" signal. Seeing an object we
    already planned means Orca re-sliced, so the old stash has to go --
    otherwise a slice whose export seam never fired leaks into the next one.
    """
    layers = build_layers()
    run_slice(plugin, layers)
    first = dict(plugin._PLAN)
    assert first

    # user moves the step up; re-slice
    tall = []
    z = LAYER_H
    while z < 2.0 + 1e-9:
        poly = box(0, 0, 10, 10) if z < 1.6 - 1e-9 else box(0, 0, 30, 10)
        tall.append(fake_orca.Layer(round(z, 3), [poly]))
        z = round(z + LAYER_H, 3)
    run_slice(plugin, tall)

    assert set(plugin._PLAN) != set(first), "stale plan survived a re-slice"
    assert all(z >= 1.6 - 1e-9 for z in plugin._PLAN), \
        f"waves left over from the previous slice: {sorted(plugin._PLAN)}"


def test_setup_check_names_both_required_settings(plugin):
    res = plugin.WaveOverhangsCheck().execute()
    assert res.status is fake_orca.PluginResult.Success, res.message
    assert "Slicing Pipeline Plugin" in res.message
    assert "Post-processing plugin" in res.message, \
        "the setup check still only tells users half the wiring"
