"""Tests for the non-planar infill engine.

Each of the first five classes pins one defect found in the reference tool
(`my-plugins/unlayered-infill/reference/nonplanar_infill_tool.py`) by running
the reference's own behaviour against the fixed engine on the same G-code.
"""
import math
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
import nonplanar_core as core  # noqa: E402


def cube_gcode(layers=10, bottom=3, top=2, size=20.0, lh=0.2):
    """A realistic OrcaSlicer export: solid bottom, sparse middle, solid top."""
    out = ["; generated by OrcaSlicer\n", "M83 ; relative extrusion\n"]
    for i in range(1, layers + 1):
        z = round(i * lh, 3)
        out += [";LAYER_CHANGE\n", f";Z:{z}\n", f";HEIGHT:{lh}\n",
                f"G1 Z{z} F600\n", ";TYPE:Outer wall\n",
                "G1 X0.000 Y0.000 E0.10000\n",
                f"G1 X{size:.3f} Y0.000 E0.80000\n",
                f"G1 X{size:.3f} Y{size:.3f} E0.80000\n",
                f"G1 X0.000 Y{size:.3f} E0.80000\n"]
        if i <= bottom:
            out.append(";TYPE:Bottom surface\n")
        elif i > layers - top:
            out.append(";TYPE:Top surface\n" if i == layers
                       else ";TYPE:Internal solid infill\n")
        else:
            out.append(";TYPE:Sparse infill\n")
        yy = 2.0
        while yy < size - 1.0:
            out.append(f"G1 X1.000 Y{yy:.3f} E0.50000\n")
            out.append(f"G1 X{size - 1:.3f} Y{yy:.3f} E0.90000\n")
            yy += 3.0
        # Real prints usually put something after the infill in the same
        # layer. This is what catches a nozzle left sitting on the wave.
        out += [";TYPE:Gap infill\n",
                f"G1 X2.000 Y{size - 1.5:.3f} E0.04000\n",
                f"G1 X{size - 2:.3f} Y{size - 1.5:.3f} E0.12000\n"]
        out += [";WIPE_START\n", f"G1 X{size - 1:.3f} Y{size - 2:.3f} E-0.80000\n"]
    out += ["; EXECUTABLE_BLOCK_END\n", f"; layer_height = {lh}\n"]
    return out


def moves(lines):
    """Extruding G1 moves as (x, y, z, e) with z None when not commanded."""
    got = []
    for ln in lines:
        w = core.parse_words(ln)
        if w and w.get("G") in (0.0, 1.0) and "E" in w and ("X" in w or "Y" in w):
            got.append((w.get("X"), w.get("Y"), w.get("Z"), w["E"]))
    return got


def total_e(lines):
    return sum(m[3] for m in moves(lines))


# ---------------------------------------------------------------------------
# 1. Extrusion belongs to the move that ENDS at the line's coordinates
# ---------------------------------------------------------------------------

def test_extrusion_is_conserved_exactly():
    src = cube_gcode()
    out, st = core.process(src, amplitude_spec="-0.2")
    assert st["moves"] > 0
    assert total_e(out) == pytest.approx(total_e(src), abs=1e-6)


def test_the_long_stroke_keeps_its_own_extrusion():
    """The 18 mm stroke carries E0.9; the reference gave it the neighbour's E0.5."""
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")

    # find the wavy segments that make up one y=2.000 stroke at some layer
    seg_e = [m[3] for m in moves(out)
             if m[1] == pytest.approx(2.0) and m[2] is not None
             and 1.0 < m[0] <= 19.0]
    assert seg_e, "no wavy segments found on the y=2 stroke"
    # 18 mm at 1 mm segments = 18 segments carrying E0.9 in total
    per = 0.9 / 18
    assert seg_e[0] == pytest.approx(per, rel=1e-3), (
        f"segment extrusion {seg_e[0]} should be 0.9/18={per:.5f}, not the "
        f"neighbouring move's 0.5/18={0.5 / 18:.5f}")


# ---------------------------------------------------------------------------
# 2. No duplicated points / zero-length extruding moves
# ---------------------------------------------------------------------------

def test_no_zero_length_extruding_moves():
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")
    prev = None
    blobs = []
    for x, y, z, e in moves(out):
        if prev is not None and e > 0 and x == prev[0] and y == prev[1]:
            blobs.append((x, y))
        prev = (x, y)
    assert not blobs, f"{len(blobs)} zero-length extruding moves (blobs)"


# ---------------------------------------------------------------------------
# 3. Z is restored when the infill stroke ends
# ---------------------------------------------------------------------------

def test_nothing_prints_at_a_stale_wavy_z():
    """Replay the file and check every non-infill extrusion runs at layer Z."""
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")

    z = 0.0
    layer_z = 0.0
    in_infill = False
    offenders = []
    for ln in out:
        name = core.section_name(ln)
        if name is not None:
            in_infill = core.is_infill_section(name)
            continue
        if ln.startswith(";Z:"):
            layer_z = float(ln[3:])
            continue
        w = core.parse_words(ln)
        if not w or w.get("G") not in (0.0, 1.0):
            continue
        if "Z" in w:
            z = w["Z"]
        if not in_infill and "E" in w and w["E"] > 0 and layer_z:
            if abs(z - layer_z) > 1e-6:
                offenders.append((ln.strip(), z, layer_z))
    assert not offenders, (
        f"{len(offenders)} non-infill extrusions ran at a displaced Z, "
        f"first: {offenders[0]}")


def test_the_wipe_after_infill_runs_on_the_layer_plane():
    """The retract/wipe follows the infill; it must not happen mid-wave."""
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")
    z = 0.0
    layer_z = 0.0
    checked = 0
    for ln in out:
        if ln.startswith(";Z:"):
            layer_z = float(ln[3:])
        w = core.parse_words(ln)
        if not w or w.get("G") not in (0.0, 1.0):
            continue
        if "Z" in w:
            z = w["Z"]
        if w.get("E", 0) < 0:                      # the wipe/retract move
            assert abs(z - layer_z) < 1e-6, (
                f"wipe ran at Z={z} but the layer is at {layer_z}")
            checked += 1
    assert checked >= 5, "no wipe moves were checked"


# ---------------------------------------------------------------------------
# 4. Orca's top/bottom skins count as solid
# ---------------------------------------------------------------------------

def test_orca_top_and_bottom_surfaces_are_found():
    src = cube_gcode(layers=10, bottom=3, top=2)
    solids = core.find_solid_layers(src)
    assert 0.2 in solids and 0.6 in solids, \
        f"'Bottom surface' layers missing from {solids}"
    assert 2.0 in solids, f"'Top surface' layer missing from {solids}"


def test_taper_measures_from_the_skin_not_the_build_plate():
    src = cube_gcode(layers=10, bottom=3, top=2)
    solids = core.find_solid_layers(src)
    # first sparse layer sits at 0.8, right above the 0.6 bottom skin
    s = core.taper_scale(0.8, solids)
    # bracketed by the 0.6 bottom skin and the 1.8 solid above:
    #   min(1.8 - 0.8, 0.8 - 0.6) / (1.8 - 0.6) = 0.2 / 1.2
    assert s == pytest.approx(0.2 / 1.2), (
        f"scale {s} suggests the taper is measured from the bed, not the skin")
    # measured from the build plate it would be min(1.0, 0.8)/1.8 = 0.444
    assert s < 0.444, "taper still looks like it starts at the build plate"
    assert s < 0.5


def test_prusa_naming_also_works():
    src = [";TYPE:Solid infill\n", "G1 Z0.2\n", ";TYPE:Internal infill\n"]
    assert core.is_solid_section("solid infill")
    assert core.is_infill_section("internal infill")
    assert core.is_infill_section("sparse infill")
    assert not core.is_infill_section("outer wall")


# ---------------------------------------------------------------------------
# 5. The taper never inverts
# ---------------------------------------------------------------------------

def test_infill_above_the_last_solid_layer_gets_no_wave():
    solids = [0.6, 1.6]
    assert core.taper_scale(2.4, solids) == 0.0     # nothing above
    assert core.taper_scale(0.2, solids) == 0.0     # nothing below
    assert core.taper_scale(1.0, solids) > 0.0      # bracketed


def test_scale_is_never_negative_anywhere_in_a_real_file():
    src = cube_gcode()
    solids = core.find_solid_layers(src)
    for i in range(1, 400):
        z = i * 0.05
        assert core.taper_scale(z, solids) >= 0.0


def test_wave_stays_within_the_requested_amplitude():
    src = cube_gcode()
    out, st = core.process(src, amplitude_spec="-0.2")
    assert st["max_wiggle"] <= 0.2 + 1e-9
    for x, y, z, e in moves(out):
        if z is not None:
            nearest = round(z / 0.2) * 0.2
            assert abs(z - nearest) <= 0.2 + 1e-6


# ---------------------------------------------------------------------------
# General behaviour
# ---------------------------------------------------------------------------

def test_absolute_extrusion_is_refused():
    src = [l.replace("M83 ; relative extrusion\n", "M82 ; absolute\n")
           for l in cube_gcode()]
    with pytest.raises(core.NonPlanarError) as e:
        core.process(src, amplitude_spec="-0.2")
    assert "relative E distances" in str(e.value)


def test_walls_are_never_touched():
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")
    wall_lines = [ln for ln in out if ln.startswith("G1 X0.000 Y0.000 E0.10000")]
    assert wall_lines, "the outer-wall moves vanished"
    assert all("Z" not in ln for ln in wall_lines)


def test_amplitude_as_percent_of_layer_height():
    src = cube_gcode(lh=0.2)
    amp, desc = core.resolve_amplitude("-150%", src)
    assert amp == pytest.approx(-0.3)
    assert "0.200" in desc
    amp, _ = core.resolve_amplitude("2x", src)
    assert amp == pytest.approx(0.4)
    amp, _ = core.resolve_amplitude("-0.25", src)
    assert amp == pytest.approx(-0.25)


def test_bad_amplitude_is_explained():
    with pytest.raises(core.NonPlanarError) as e:
        core.resolve_amplitude("wavy", cube_gcode())
    assert "Could not understand" in str(e.value)


def test_a_file_with_no_infill_is_returned_unchanged():
    src = ["M83\n", "G1 Z0.2\n", ";TYPE:Outer wall\n",
           "G1 X1.000 Y1.000 E0.10000\n", "G1 X9.000 Y1.000 E0.50000\n"]
    out, st = core.process(src, amplitude_spec="-0.2")
    assert out == src
    assert st["moves"] == 0


def test_frequency_changes_the_wave():
    src = cube_gcode()
    a, _ = core.process(src, amplitude_spec="-0.2", frequency=1.5)
    b, _ = core.process(src, amplitude_spec="-0.2", frequency=4.0)
    assert a != b


def test_zero_amplitude_leaves_geometry_flat():
    src = cube_gcode()
    out, st = core.process(src, amplitude_spec="0")
    assert st["max_wiggle"] == 0.0
    for x, y, z, e in moves(out):
        if z is not None:
            assert abs(z - round(z / 0.2) * 0.2) < 1e-9


def test_stats_describe_what_happened():
    src = cube_gcode()
    _, st = core.process(src, amplitude_spec="-0.2")
    assert st["sections"] == 5          # layers 4..8 are sparse
    assert st["moves"] > 0
    assert st["segments"] > st["moves"]
    assert st["extrusion_mode"] == "relative"
    assert st["solid_layers"] == 5      # 0.2 0.4 0.6 bottom skin, 1.8 solid, 2.0 top
    assert 0 < st["max_wiggle"] <= 0.2


def test_segment_length_controls_resolution():
    src = cube_gcode()
    _, coarse = core.process(src, amplitude_spec="-0.2", segment_mm=3.0)
    _, fine = core.process(src, amplitude_spec="-0.2", segment_mm=0.5)
    assert fine["segments"] > coarse["segments"]
    assert fine["moves"] == coarse["moves"]
