"""Tests for the non-planar infill engine.

Each of the first five classes pins one defect found in the reference tool
(`my-plugins/unlayered-infill/reference/nonplanar_infill_tool.py`) by running
the reference's own behaviour against the fixed engine on the same G-code.
"""
import math
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
import nonplanar_core as core  # noqa: E402


def cube_gcode(layers=10, bottom=3, top=2, size=20.0, lh=0.2):
    """A realistic OrcaSlicer export: solid bottom, sparse middle, solid top."""
    out = ["; generated by OrcaSlicer\n", "M83 ; relative extrusion\n"]
    for i in range(1, layers + 1):
        z = round(i * lh, 3)
        out += [";LAYER_CHANGE\n", f";Z:{z}\n", f";HEIGHT:{lh}\n",
                f"G1 Z{z} F600\n", ";TYPE:Outer wall\n",
                "G1 X0.000 Y0.000 E0.10000\n",
                f"G1 X{size:.3f} Y0.000 E0.80000\n",
                f"G1 X{size:.3f} Y{size:.3f} E0.80000\n",
                f"G1 X0.000 Y{size:.3f} E0.80000\n"]
        if i <= bottom:
            out.append(";TYPE:Bottom surface\n")
        elif i > layers - top:
            out.append(";TYPE:Top surface\n" if i == layers
                       else ";TYPE:Internal solid infill\n")
        else:
            out.append(";TYPE:Sparse infill\n")
        yy = 2.0
        while yy < size - 1.0:
            out.append(f"G1 X1.000 Y{yy:.3f} E0.50000\n")
            out.append(f"G1 X{size - 1:.3f} Y{yy:.3f} E0.90000\n")
            yy += 3.0
        # Real prints usually put something after the infill in the same
        # layer. This is what catches a nozzle left sitting on the wave.
        out += [";TYPE:Gap infill\n",
                f"G1 X2.000 Y{size - 1.5:.3f} E0.04000\n",
                f"G1 X{size - 2:.3f} Y{size - 1.5:.3f} E0.12000\n"]
        out += [";WIPE_START\n", f"G1 X{size - 1:.3f} Y{size - 2:.3f} E-0.80000\n"]
    out += ["; EXECUTABLE_BLOCK_END\n", f"; layer_height = {lh}\n"]
    return out


def moves(lines):
    """Extruding G1 moves as (x, y, z, e) with z None when not commanded."""
    got = []
    for ln in lines:
        w = core.parse_words(ln)
        if w and w.get("G") in (0.0, 1.0) and "E" in w and ("X" in w or "Y" in w):
            got.append((w.get("X"), w.get("Y"), w.get("Z"), w["E"]))
    return got


def total_e(lines):
    return sum(m[3] for m in moves(lines))


# ---------------------------------------------------------------------------
# 1. Extrusion belongs to the move that ENDS at the line's coordinates
# ---------------------------------------------------------------------------

def test_extrusion_is_conserved_exactly():
    src = cube_gcode()
    out, st = core.process(src, amplitude_spec="-0.2")
    assert st["moves"] > 0
    assert total_e(out) == pytest.approx(total_e(src), abs=1e-6)


def test_the_long_stroke_keeps_its_own_extrusion():
    """The 18 mm stroke carries E0.9; the reference gave it the neighbour's E0.5."""
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")

    # find the wavy segments that make up one y=2.000 stroke at some layer
    seg_e = [m[3] for m in moves(out)
             if m[1] == pytest.approx(2.0) and m[2] is not None
             and 1.0 < m[0] <= 19.0]
    assert seg_e, "no wavy segments found on the y=2 stroke"
    # 18 mm at 1 mm segments = 18 segments carrying E0.9 in total
    per = 0.9 / 18
    assert seg_e[0] == pytest.approx(per, rel=1e-3), (
        f"segment extrusion {seg_e[0]} should be 0.9/18={per:.5f}, not the "
        f"neighbouring move's 0.5/18={0.5 / 18:.5f}")


# ---------------------------------------------------------------------------
# 2. No duplicated points / zero-length extruding moves
# ---------------------------------------------------------------------------

def test_no_zero_length_extruding_moves():
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")
    prev = None
    blobs = []
    for x, y, z, e in moves(out):
        if prev is not None and e > 0 and x == prev[0] and y == prev[1]:
            blobs.append((x, y))
        prev = (x, y)
    assert not blobs, f"{len(blobs)} zero-length extruding moves (blobs)"


# ---------------------------------------------------------------------------
# 3. Z is restored when the infill stroke ends
# ---------------------------------------------------------------------------

def test_nothing_prints_at_a_stale_wavy_z():
    """Replay the file and check every non-infill extrusion runs at layer Z."""
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")

    z = 0.0
    layer_z = 0.0
    in_infill = False
    offenders = []
    for ln in out:
        name = core.section_name(ln)
        if name is not None:
            in_infill = core.is_infill_section(name)
            continue
        if ln.startswith(";Z:"):
            layer_z = float(ln[3:])
            continue
        w = core.parse_words(ln)
        if not w or w.get("G") not in (0.0, 1.0):
            continue
        if "Z" in w:
            z = w["Z"]
        if not in_infill and "E" in w and w["E"] > 0 and layer_z:
            if abs(z - layer_z) > 1e-6:
                offenders.append((ln.strip(), z, layer_z))
    assert not offenders, (
        f"{len(offenders)} non-infill extrusions ran at a displaced Z, "
        f"first: {offenders[0]}")


def test_the_wipe_after_infill_runs_on_the_layer_plane():
    """The retract/wipe follows the infill; it must not happen mid-wave."""
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")
    z = 0.0
    layer_z = 0.0
    checked = 0
    for ln in out:
        if ln.startswith(";Z:"):
            layer_z = float(ln[3:])
        w = core.parse_words(ln)
        if not w or w.get("G") not in (0.0, 1.0):
            continue
        if "Z" in w:
            z = w["Z"]
        if w.get("E", 0) < 0:                      # the wipe/retract move
            assert abs(z - layer_z) < 1e-6, (
                f"wipe ran at Z={z} but the layer is at {layer_z}")
            checked += 1
    assert checked >= 5, "no wipe moves were checked"


def solid_heights(src):
    """The Z heights carrying a skin, anywhere in the part."""
    return core.build_solid_grid(src)[1]


def scale_at(src, z, x=5.0, y=5.0, **kw):
    """Taper at a point, through the column grid."""
    return core.build_solid_grid(src, kw.pop("cell_mm", core.DEFAULT_CELL_MM))[0] \
               .scale(x, y, z, kw.pop("full_strength", False),
                      kw.pop("blend_mm", core.DEFAULT_BLEND_MM))


# ---------------------------------------------------------------------------
# 4. Orca's top/bottom skins count as solid
# ---------------------------------------------------------------------------

def test_orca_top_and_bottom_surfaces_are_found():
    src = cube_gcode(layers=10, bottom=3, top=2)
    solids = solid_heights(src)
    assert 0.2 in solids and 0.6 in solids, \
        f"'Bottom surface' layers missing from {solids}"
    assert 2.0 in solids, f"'Top surface' layer missing from {solids}"


def test_taper_measures_from_the_skin_not_the_build_plate():
    src = cube_gcode(layers=10, bottom=3, top=2)
    # first sparse layer sits at 0.8, right above the 0.6 bottom skin
    s = scale_at(src, 0.8)
    # bracketed by the 0.6 bottom skin and the 1.8 solid above:
    #   min(1.8 - 0.8, 0.8 - 0.6) / (1.8 - 0.6) = 0.2 / 1.2
    assert s == pytest.approx(0.2 / 1.2), (
        f"scale {s} suggests the taper is measured from the bed, not the skin")
    # measured from the build plate it would be min(1.0, 0.8)/1.8 = 0.444
    assert s < 0.444, "taper still looks like it starts at the build plate"
    assert s < 0.5


def test_prusa_naming_also_works():
    src = [";TYPE:Solid infill\n", "G1 Z0.2\n", ";TYPE:Internal infill\n"]
    assert core.is_solid_section("solid infill")
    assert core.is_infill_section("internal infill")
    assert core.is_infill_section("sparse infill")
    assert not core.is_infill_section("outer wall")


# ---------------------------------------------------------------------------
# 5. The taper never inverts
# ---------------------------------------------------------------------------

def test_infill_above_the_last_solid_layer_gets_no_wave():
    src = cube_gcode(layers=10, bottom=3, top=2)   # skins at 0.2-0.6 and 1.8-2.0
    assert scale_at(src, 3.0) == 0.0     # nothing above
    assert scale_at(src, 0.1) == 0.0     # nothing below
    assert scale_at(src, 1.2) > 0.0      # bracketed


def test_scale_is_never_negative_anywhere_in_a_real_file():
    src = cube_gcode()
    grid, _ = core.build_solid_grid(src)
    for i in range(1, 400):
        z = i * 0.05
        assert grid.scale(5.0, 5.0, z) >= 0.0


def test_wave_stays_within_the_requested_amplitude():
    src = cube_gcode()
    out, st = core.process(src, amplitude_spec="-0.2")
    assert st["max_wiggle"] <= 0.2 + 1e-9
    for x, y, z, e in moves(out):
        if z is not None:
            nearest = round(z / 0.2) * 0.2
            assert abs(z - nearest) <= 0.2 + 1e-6


# ---------------------------------------------------------------------------
# General behaviour
# ---------------------------------------------------------------------------

def test_absolute_extrusion_is_refused():
    src = [l.replace("M83 ; relative extrusion\n", "M82 ; absolute\n")
           for l in cube_gcode()]
    with pytest.raises(core.NonPlanarError) as e:
        core.process(src, amplitude_spec="-0.2")
    assert "relative E distances" in str(e.value)


def test_walls_are_never_touched():
    src = cube_gcode()
    out, _ = core.process(src, amplitude_spec="-0.2")
    wall_lines = [ln for ln in out if ln.startswith("G1 X0.000 Y0.000 E0.10000")]
    assert wall_lines, "the outer-wall moves vanished"
    assert all("Z" not in ln for ln in wall_lines)


def test_amplitude_as_percent_of_layer_height():
    src = cube_gcode(lh=0.2)
    amp, desc = core.resolve_amplitude("-150%", src)
    assert amp == pytest.approx(-0.3)
    assert "0.200" in desc
    amp, _ = core.resolve_amplitude("2x", src)
    assert amp == pytest.approx(0.4)
    amp, _ = core.resolve_amplitude("-0.25", src)
    assert amp == pytest.approx(-0.25)


def test_bad_amplitude_is_explained():
    with pytest.raises(core.NonPlanarError) as e:
        core.resolve_amplitude("wavy", cube_gcode())
    assert "Could not understand" in str(e.value)


def test_a_file_with_no_infill_is_returned_unchanged():
    src = ["M83\n", "G1 Z0.2\n", ";TYPE:Outer wall\n",
           "G1 X1.000 Y1.000 E0.10000\n", "G1 X9.000 Y1.000 E0.50000\n"]
    out, st = core.process(src, amplitude_spec="-0.2")
    assert out == src
    assert st["moves"] == 0


def test_frequency_changes_the_wave():
    src = cube_gcode()
    a, _ = core.process(src, amplitude_spec="-0.2", frequency=1.5)
    b, _ = core.process(src, amplitude_spec="-0.2", frequency=4.0)
    assert a != b


def test_zero_amplitude_leaves_geometry_flat():
    src = cube_gcode()
    out, st = core.process(src, amplitude_spec="0")
    assert st["max_wiggle"] == 0.0
    for x, y, z, e in moves(out):
        if z is not None:
            assert abs(z - round(z / 0.2) * 0.2) < 1e-9


def test_stats_describe_what_happened():
    src = cube_gcode()
    _, st = core.process(src, amplitude_spec="-0.2")
    assert st["sections"] == 5          # layers 4..8 are sparse
    assert st["moves"] > 0
    assert st["segments"] > st["moves"]
    assert st["extrusion_mode"] == "relative"
    assert st["solid_layers"] == 5      # 0.2 0.4 0.6 bottom skin, 1.8 solid, 2.0 top
    assert 0 < st["max_wiggle"] <= 0.2


def test_segment_length_controls_resolution():
    src = cube_gcode()
    _, coarse = core.process(src, amplitude_spec="-0.2", segment_mm=3.0)
    _, fine = core.process(src, amplitude_spec="-0.2", segment_mm=0.5)
    assert fine["segments"] > coarse["segments"]
    assert fine["moves"] == coarse["moves"]


# ---------------------------------------------------------------------------
# 6. Solid skins are mapped per XY column, not globally
# ---------------------------------------------------------------------------

def two_tower_gcode():
    """Two towers of different heights sharing a build plate.

    Tower A (x 0-8) is capped at z=1.0. Tower B (x 12-20) runs on to z=3.0.
    Nothing in tower B has a skin at z=1.0 — but a global list of solid
    heights contains 1.0, because tower A put it there.
    """
    out = ["M83 ; relative extrusion\n"]
    z = 0.2
    while z < 3.0001:
        out.append(f";LAYER_CHANGE\n;Z:{z:.1f}\n;HEIGHT:0.2\n")
        out.append(f"G1 Z{z:.1f} F600\n")
        for name, x0, x1, top in (("A", 1.0, 8.0, 1.0), ("B", 12.0, 19.0, 3.0)):
            if z > top + 1e-9:
                continue
            if abs(z - 0.2) < 1e-9:
                kind = "Bottom surface"
            elif abs(z - top) < 1e-9:
                kind = "Top surface"
            else:
                kind = "Sparse infill"
            out.append(f";TYPE:{kind}\n")
            for i in range(6):          # a few passes so columns get covered
                y = 1.0 + i * 1.5
                out.append(f"G1 X{x0:.3f} Y{y:.3f} F9000\n")
                out.append(f"G1 X{x1:.3f} Y{y:.3f} E0.90000 F1800\n")
        z = round(z + 0.2, 4)
    return out


def test_a_tall_tower_ignores_a_short_neighbours_roof():
    """The bug a global solid list causes, measured.

    Tower A's top skin at z=1.0 is in the global list, so global bracketing
    pinches the taper to zero at z=1.0 *everywhere* — including inside tower
    B, which has no skin there. That plants a flat, unwoven plane right
    through the tall tower: exactly the layer-boundary weakness the whole
    tool exists to remove.
    """
    src = two_tower_gcode()
    grid, solids = core.build_solid_grid(src)
    assert 1.0 in solids and 3.0 in solids, solids

    in_b = grid.scale(15.0, 4.0, 1.0)      # inside tower B, at A's roof height
    assert in_b > 0.1, (
        f"tower B pinches to {in_b:.4f} at z=1.0 — it is still being bracketed "
        "against tower A's roof")

    in_a_roof = grid.scale(4.0, 4.0, 1.0)  # inside tower A, at its own roof
    assert in_a_roof == pytest.approx(0.0, abs=1e-6), (
        f"tower A must stay flat at its own skin, got {in_a_roof:.4f}")


def test_each_column_tapers_against_its_own_roof():
    """At the same Z, the two towers must get different answers.

    The taper is a fraction of the column's own floor-to-roof span, so at
    z=0.8 tower A (skins 0.2 and 1.0) sits at 0.2/0.8 = 0.25 of its span,
    while tower B (skins 0.2 and 3.0) sits at 0.6/2.8 = 0.214 of its much
    taller one. A global solid list would hand both columns tower A's answer,
    because 1.0 would be the nearest solid above in both.
    """
    src = two_tower_gcode()
    grid, _ = core.build_solid_grid(src)
    a = grid.scale(4.0, 4.0, 0.8)
    b = grid.scale(15.0, 4.0, 0.8)

    assert a == pytest.approx(0.2 / 0.8, abs=0.01), a
    assert b == pytest.approx(0.6 / 2.8, abs=0.01), (
        f"tower B got {b:.4f}; bracketed against tower A's roof it would be "
        f"{0.2 / 0.8:.4f}")
    assert a != pytest.approx(b, abs=0.01), (
        "both towers got the same taper, so columns are not independent")


def test_the_wave_never_reaches_a_skin_in_its_own_column():
    """Amplitude x taper must stay inside the gap to the nearest local skin."""
    src = two_tower_gcode()
    grid, _ = core.build_solid_grid(src)
    amp = 0.2
    for x in (4.0, 15.0):
        for i in range(2, 15):
            z = round(i * 0.2, 4)
            zs = grid.columns.get(grid.key(x, 4.0))
            if not zs:
                continue
            gap = min((abs(s - z) for s in zs), default=None)
            if gap is None or gap < 1e-9:
                continue
            dz = amp * grid.scale(x, 4.0, z)
            assert dz <= gap + 1e-9, (
                f"at x={x} z={z} the wave moves {dz:.4f} mm but the nearest "
                f"skin in that column is only {gap:.4f} mm away")


# ---------------------------------------------------------------------------
# 7. Blending across column seams
# ---------------------------------------------------------------------------

def ledge_grid(cell=0.6):
    """Columns left of x=10 are capped at z=1.0, right of it at z=3.0."""
    g = core.SolidGrid(cell)
    for x in range(0, 100):
        xx = x * 0.2
        g.add_move(xx, 0.0, xx, 8.0, 0.2)
        g.add_move(xx, 0.0, xx, 8.0, 1.0 if xx < 10.0 else 3.0)
    return g.finalize()


def biggest_step(grid, blend):
    vals = [grid.scale(8.0 + i * 0.1, 4.0, 0.8, False, blend) for i in range(41)]
    return max(abs(b - a) for a, b in zip(vals, vals[1:]))


def test_blending_smooths_the_step_at_a_ledge():
    """Without blending the taper jumps at the column seam; with it, it ramps."""
    hard = biggest_step(ledge_grid(), blend=0.0)
    soft = biggest_step(ledge_grid(), blend=core.DEFAULT_BLEND_MM)
    assert soft < hard / 2.0, (
        f"blending barely helped: worst step {soft:.5f} vs {hard:.5f} unblended")


def test_blending_does_not_move_the_taper_far_from_the_local_answer():
    grid = ledge_grid()
    for x in (2.0, 18.0):        # well away from the seam
        near = grid.scale(x, 4.0, 0.8, False, 0.0)
        blended = grid.scale(x, 4.0, 0.8, False, core.DEFAULT_BLEND_MM)
        assert blended == pytest.approx(near, abs=0.02), (
            f"blending shifted the taper at x={x}: {blended:.4f} vs {near:.4f}")


# ---------------------------------------------------------------------------
# 8. Full-strength mode
# ---------------------------------------------------------------------------

def test_classic_math_caps_the_wave_at_half_amplitude():
    src = cube_gcode(layers=20, bottom=2, top=2)
    grid, _ = core.build_solid_grid(src)
    peak = max(grid.scale(5.0, 5.0, round(i * 0.2, 4)) for i in range(2, 20))
    assert peak <= 0.5 + 1e-9, f"classic taper exceeded 0.5: {peak}"


def test_full_strength_reaches_the_whole_amplitude_mid_span():
    src = cube_gcode(layers=20, bottom=2, top=2)
    grid, _ = core.build_solid_grid(src)
    peak = max(grid.scale(5.0, 5.0, round(i * 0.2, 4), True) for i in range(2, 20))
    assert peak > 0.9, f"full strength only reached {peak:.4f}"
    assert peak <= 1.0 + 1e-9, f"full strength overshot: {peak}"


def test_full_strength_still_fades_to_zero_at_the_skins():
    src = cube_gcode(layers=20, bottom=2, top=2)
    grid, _ = core.build_solid_grid(src)
    assert grid.scale(5.0, 5.0, 0.4, True) == pytest.approx(0.0, abs=1e-6)
    assert grid.scale(5.0, 5.0, 4.0, True) == pytest.approx(0.0, abs=1e-6)


def test_full_strength_doubles_the_wiggle_end_to_end():
    src = cube_gcode(layers=20, bottom=2, top=2)
    _, half = core.process(src, amplitude_spec="-0.2")
    _, full = core.process(src, amplitude_spec="-0.2", full_strength=True)
    assert full["max_wiggle"] > half["max_wiggle"] * 1.7, (
        f"{full['max_wiggle']:.4f} vs {half['max_wiggle']:.4f}")
    assert full["max_wiggle"] <= 0.2 + 1e-9


# ---------------------------------------------------------------------------
# 9. Running twice must not wave twice
# ---------------------------------------------------------------------------

def test_a_second_pass_changes_nothing():
    """Orca can call the export step twice for one slice (file + upload)."""
    src = cube_gcode()
    once, st1 = core.process(src)
    assert st1["moves"] > 0 and not st1["already_processed"]
    twice, st2 = core.process(once)
    assert st2["already_processed"] is True
    assert st2["moves"] == 0
    assert twice == once, "the second pass modified an already-waved file"


def test_the_marker_is_written_once_and_is_findable():
    out, _ = core.process(cube_gcode())
    markers = [l for l in out if l.startswith(core.MARKER_PREFIX)]
    assert len(markers) == 1, markers
    assert core.MARKER_VERSION in markers[0]
    assert core.already_processed(out)
    assert not core.already_processed(cube_gcode())


def test_a_file_with_no_waves_is_not_marked():
    """Nothing was changed, so nothing should claim it was."""
    src = [l for l in cube_gcode() if "Sparse infill" not in l]
    out, st = core.process(src)
    assert st["moves"] == 0
    assert not core.already_processed(out), \
        "an untouched file was stamped, so a later real run would skip it"
